import { ChoiceOption } from "./choiceOption";

export interface Question {
    'id': string,
    'displayTex': string,
    'responseMaxLength': string,
    'numberLevel': string,
    'type': string,
    'isMandatory': boolean,
    'mandatoryIndicator': string,
    'isImportant': boolean,
    'importantIndicator': string,
    'hasDependentQuestion': boolean,
    'responseToDisplayDependentQuestionBoolean': boolean,
    'responseToDisplayDependentQuestionList': string,
    'responseToDisplayDependentQuestionStartDate': string,
    'responseToDisplayDependentQuestionEndDate': string,
    'additionalInfoRequired': boolean,
    'additionalInfoLabel': string,
    'responseToRequireAdditionalInfoBoolean': boolean,
    'responseToRequireAdditionalInfoList': string,
    'responseToRequireAdditionalInfoStartDate': string,
    'responseToRequireAdditionalInfoEndDate': string,
    'requiresNotification': boolean,
    'responseToRequireNotificationBoolean': boolean,
    'responseToRequireNotificationList': string,
    'responseToRequireNotificationStartDate': string,
    'responseToRequireNotificationEndDate': string,
    'tooltipText': string,
    'hasHardStop': boolean,
    'maximumNumberOfCheckboxes': string,
    'furtherInstructions': string,
    'textValidRange': string,
    'textInvalidRange': string,
    'isVisible': boolean,
    'multilevelChoiceDef': string,
    'expandAdditionalInfo': boolean,
    'choiceOptions': ChoiceOption[],
    'dependentQuestions': Question[],
    'response': string,
    'responseLabel': string,
    'responseLabels': string[],
    'additionalInfoResponse': string,
    'lastUpdated': string,
    'lastUpdatedFirstName': string,
    'lastUpdatedLastName': string,
    'isRemediated': boolean,
    'hasAlertFlag': boolean,
    'hasSkippedFlag': boolean

}